version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_DATABASE=database.sqlite
      - PORT=3001
    ports:
      - "3001:3001"
